### ISSUE TITLE
non-public dependency?

### ISSUE THREAD

**Issue by wyattbenno777** [joshbeal/mira#3]
I get this when trying to run `cargo re-groth16-dev `

I think the issue is here?

`[dependencies.halo2_proofs]
git = "https://github.com/joshbeal/halo2"
branch = "joshbeal/dev-mira"`

Updating git repository `https://github.com/joshbeal/halo2`
error: failed to get `halo2_proofs` as a dependency of package `mira v0.2.0 (/Users/wyattbenno/Desktop/mira)`

Caused by:
  failed to load source for dependency `halo2_proofs`

Caused by:
  Unable to update https://github.com/joshbeal/halo2?branch=joshbeal/dev-mira

**Comment by joshbeal** [comment]
This should be fixed now. The dependency changes are minimal (i.e., modifying group struct visibility).
